title: "Tarun Bhatt"
description: "Essays on AI/ML, business operations, and manufacturing innovation."
url: "https://belman.us"
baseurl: ""

markdown: kramdown
highlighter: rouge

# Removed global permalink setting as you want to define it in each post's front matter
future: false
