title: "Tarun Bhatt"
description: "Essays on AI/ML, business operations, and manufacturing innovation."
baseurl: ""
url: "https://belman.us"

markdown: kramdown
highlighter: rouge

permalink: /:title/
future: true
